version: "3.9"

services:
  db:
    image: postgres:15
    container_name: oripa-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: oripa
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: oripa-server
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/oripa
      NODE_ENV: development
      ALLOWED_ORIGINS: http://localhost:4200,http://localhost:4300

  client:
    build: ./client
    container_name: oripa-client
    ports:
      - "4300:4200"
    depends_on:
      - server

volumes:
  db-data: